name: .NET Build
description: "Builds a .NET solution."
inputs:
  directory:
    description: "Directory containing the solution."
    required: false
    default: "."
  name:
    description: "Name of the solution, used in the name for the coverage summary."
    required: false
    default: ""
  coverage-assembly-filters:
    description: "Optional filter to apply when merging code coverage reports."
    required: false
    default: ""

runs:
  using: composite

  steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 9.0.x

    - name: Restore Dependencies
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet restore

    - name: Verify Code Is Correctly Formatted
      continue-on-error: true
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet format --verify-no-changes

    - name: Build
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet build --no-restore --configuration Release

    - name: Test
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet test --no-restore --no-build --configuration Release -- --coverage --coverage-output coverage.xml --coverage-output-format cobertura

    - name: Merge Code Coverage Reports
      if: success() || failure()
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        dotnet new tool-manifest
        dotnet tool install dotnet-reportgenerator-globaltool
        dotnet tool run reportgenerator "-reports:**/TestResults/**/coverage.xml" "-targetdir:." "-reportTypes:Cobertura"${{ inputs.coverage-assembly-filters != '' && format(' -assemblyfilters:{0}', inputs.coverage-assembly-filters) || '' }}
        
    - name: Upload Code Coverage to DeepSource
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        curl https://deepsource.io/cli | sh
        ./bin/deepsource report --analyzer test-coverage --key csharp --value-file ./Cobertura.xml

    - name: Generate Code Coverage Summary
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.directory }}/Cobertura.xml
        format: markdown
        indicators: true
        output: file
        thresholds: '90 95'

      # Perform last in case they fail for being too big at some point.
    - name: Add Code Coverage Summary to Job Summary
      shell: bash
      run: |
        echo "# ${{ inputs.name }} Coverage Report" >> $GITHUB_STEP_SUMMARY
        cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
        echo "---" >> $GITHUB_STEP_SUMMARY
