name: .NET Build
description: "Builds a .NET solution."
inputs:
  directory:
    description: "Directory containing the solution."
    required: true
  name:
    description: "Name of the solution."
    required: false
    default: ""
  assembly-filter:
    description: "Optional code coverage assembly filter."
    required: false
    default: "+*"

runs:
  using: composite

  steps:
    - name: Restore Dependencies
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet restore

    - name: Verify Code Is Correctly Formatted
      continue-on-error: true
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet format --verify-no-changes

    - name: Build
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet build --no-restore --configuration Release

    - name: Install dotnet-coverage
      shell: bash
      run: dotnet tool install -g dotnet-coverage

    - name: Test
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet test --no-restore --no-build --configuration Release --logger "trx;LogFileName=test-results.trx" --collect:"Code Coverage;Format=cobertura;IncludeTestAssembly=false;"

    - name: Test Report
      uses: dorny/test-reporter@v1.9.0
      if: success() || failure()
      with:
        name: ${{ inputs.name }} Test Results
        path: "${{ inputs.directory }}/**/TestResults/test-results.trx"
        reporter: dotnet-trx

    - name: Merge Coverage Reports
      shell: bash
      working-directory: ${{ inputs.directory }}
      run: dotnet-coverage merge -f cobertura -o coverage.xml ./**/TestResults/**/*.cobertura.xml

    - name: Generate Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: ${{ inputs.directory }}/coverage.xml
        format: markdown
        indicators: true
        output: file
        thresholds: '90 95'

    - name: Attach Coverage Report to Build
      uses: dtinth/markdown-report-action@v1
      with:
        name: ${{ inputs.name }} Test Coverage
        title: ${{ inputs.name }} Test Coverage
        body-file: code-coverage-results.md
